embeds:
  - title: Barbara
    color: ${ COLORS.HYDRO_BLUE }
    image: 
      url: ${INFOGRAPHICS.BARBARA_!}
    thumbnail:
      url: "https://muakasan.github.io/genshin-portraits/assets/UI_AvatarIcon_Barbara.png"
    description: |-
      *Every citizen of Mondstadt adores Barbara. She learned the word "idol" from a magazine.*
    footer:
      text: "Use \"Open original\" to view full size. Page 2 Coming Soon!\n\nCredits to: Artesians#0002 (Designer) | xf3#3123 (Content)"      


buttons:
  - customId: "liveInteraction#characters/hydro/barbara/build"
    label: "Teams Infographic"
    style: "PRIMARY"
    emoji: "▶️"

  - label: "Guide"
    url: "https://keqingmains.com/barbara"
    emoji: ${ EMOJIS.LOGO }
    style: "LINK"

  - label: "Quick Guide"
    url: "https://keqingmains.com/q/barbara-quickguide/"
    emoji: ${ EMOJIS.LOGO }
    style: "LINK"

  - label: "TCL"
    url: "https://library.keqingmains.com/barbara"
    emoji: ${ EMOJIS.MAGNIFY }
    style: "LINK"

#  - label: "Video Guide"
#    url: "https://www.youtube.com/watch?v=QW40leHPgJ8"
#    emoji: ${ EMOJIS.YOUTUBE }
#    style: "LINK"